#!/bin/sh
 
# These environment variables are sometimes needed by the running daemons
export USER=slup0000
export HOME=/home/slup0000
 
# Include the user-specific profile
. $HOME/.bash_profile
 
# Now let's go!
cd $HOME/rpchatbot/
exec /usr/local/bin/python3.6 -u $HOME/rpcharbot/bot.py 2>&1
